### ISSUE TITLE
Export file to Whitelist

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/BurntChrome#17]
See https://developer.chrome.com/apps/fileSystem
Maybe `chooseEntry` for obtaining a file to read from and load the Whitelist.

**Comment by occamrazor1492** [comment]
@Glavin001 I have one question, I want to make the front page like when I click the "choose entry button " and then the two text edit area would appear
![3642e2ee-6536-4dec-9370-5f6c5d40ec98](https://cloud.githubusercontent.com/assets/3355559/13996164/513b948c-f10b-11e5-8552-e273afe988ed.png)
Could you give me a link of how to implement that or where I can imitate the same as you did in the html page? Thank you so much

**Comment by occamrazor1492** [comment]
Another problem is that I only write the function in background.js, but I see some function in popup.js, could you tell me when do I need to write in popup.js, I am not so clear about that, sorry.

**Comment by Glavin001** [comment]
I think it may be easier if we do not have it show/hide parts, such as clicking "choose entry" and showing a new group of elements. I recommend that you keep the view being static, at least for now.

I recommend you implement the following interface:

In `popup.js`:
- [ ] Save to file button
  - [ ] Call `this.background.moderator. getWhitelistJSON()`
  - [ ] Save that JSON to the file
- [ ] Load from file button
  - [ ] Read text from given file
  - [ ] `JSON.parse` the text into a JSON object in-memory
  - [ ] Call `this.background.moderator.setWhitelistJSON(newJSON)`. Note that this method does not already exist, yet.

In `background.js`:
- [ ] Add method `setWhitelistJSON` to `Moderator` class
  - See `getWhitelistJSON`: https://github.com/Glavin001/BurntChrome/blob/master/extension/src/background.js#L403-L410
  - Implement something similar that calls `whitelist.set(newJSON)`.

**Comment by Glavin001** [comment]
Take a look at https://github.com/mozilla/seasponge/blob/e483739c8c820a50eabb0754791331af559395c8/app/scripts/controllers/draw.coffee#L149-L173

``` coffeescript
    downloadData = (name, data, type) ->
        # Browser support
        window.URL = window.URL || window.webkitURL;
        # Arg defaults
        type = type || "text/plain";
        name = name || "download"
        data = data || ""
        # Create Blob
        if data instanceof Blob
            blob = data
        else
            blob = new Blob([data], {type: type})
        url = window.URL.createObjectURL(blob)
        # Create link
        link = document.createElement("a")
        link.download = name
        link.href = url
        # Download!
        # See http://stackoverflow.com/a/25047811/2578205 for more details
        event = document.createEvent("MouseEvents")
        event.initMouseEvent(
                "click", true, false, window, 0, 0, 0, 0, 0
                , false, false, false, false, 0, null
        )
        link.dispatchEvent(event)
```
