### ISSUE TITLE
Data validation for input forms

### ISSUE THREAD

**Issue by ghost** [Glavin001/BurntChrome#21]

**Comment by ghost** [comment]
It seems that using HTML5 form validation requires some awkward workarounds if you aren't actually using the submit mechanism. I'm thinking of adding the validation into popup.js and inserting feedback text into popup.html if there's an issue. Thoughts?

**Comment by Glavin001** [comment]
You _could_ use the HTML `form` tag if you wanted, and hijack the submitting event with something like http://stackoverflow.com/a/14881917/2578205

**Comment by ghost** [comment]
Yeah, that's one of the workarounds I didn't necessarily want to use. I'll give it a try tomorrow.

**Comment by Glavin001** [comment]
Can this issue be closed?
