### ISSUE TITLE
If user inputs a url that already exists in the whitelist, no message is displayed.

### ISSUE THREAD

**Issue by LizardLeliel** [Glavin001/BurntChrome#30]
In fact, nothing happens. The url will remain in the "url" textbox, even after you click "add to whitelist". This can possible confuse users. I suggest to add a red-text message similar to one that appears if the username or password is invalid.

**Comment by LizardLeliel** [comment]
Please keep in mind it could also be my Burnt Chrome extension not working right because that's happened very often.

**Comment by Glavin001** [comment]
Check the source code. _Should_ there be something that happens? Can you find what line(s) of code are not working as expected?

**Comment by Glavin001** [comment]
This is working with PR #28.

![image](https://cloud.githubusercontent.com/assets/1885333/14091260/8b80809a-f515-11e5-9ea0-5ffbabb49dbd.png)
