### ISSUE TITLE
Authentication component

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/BurntChrome#9]
- [x] Read and understand:
  - [x] https://developer.chrome.com/apps/identity
  - [x] https://developer.chrome.com/apps/app_identity
- [x] Login with Google Account
- [x] Retrieve the profile User info, to get their `email` address.
  - `chrome.identity.getProfileUserInfo`
- [x] Authentication system API Interface

```
Auth.login(function(userInfo) {
  // Userinfo looks like { email: '...', id: '...' }
  // Pass the user info to Whitelist system
});
```

**Comment by Glavin001** [comment]
I hate this. This is what I was worried about.

I am giving up. I am unable to call:

``` javascript
chrome.identity.getAuthToken({interactive:true}, function() { console.log(arguments); });
```

I receive the following error message:

```
Unchecked runtime.lastError while running identity.getAuthToken: Invalid OAuth2 Client ID.reportIfUnchecked @ extensions::lastError:133handleResponse @ extensions::sendRequest:78
```

Things to read:
- Invalid OAuth2 Client ID while chrome.identity.getAuthToken: http://stackoverflow.com/questions/31110795/invalid-oauth2-client-id-while-chrome-identity-getauthtoken
- Obtaining Chrome Extension ID for development: http://stackoverflow.com/a/23877974/2578205
- How to change chrome packaged app id Or Why do we need key field in the manifest.json?: http://stackoverflow.com/a/21500707/2578205
- Packaging: https://developer.chrome.com/extensions/packaging
- Add your existing web app to Chrome Web Store: https://developer.chrome.com/webstore/get_started_simple
- chrome.identity.getAuthToken not working: http://stackoverflow.com/a/31157734/2578205
- User authentication: https://developer.chrome.com/apps/app_identity#update_manifest
- Is it possible to create a Chrome Extension for private distribution outside Chrome Web Store?: http://stackoverflow.com/questions/12452817/is-it-possible-to-create-a-chrome-extension-for-private-distribution-outside-chr
- how to get chrome.identity.getAuthToken() working?: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/HMe3mqCRObc
- chrome.identity User Authentication in a Chrome Extension: http://stackoverflow.com/a/25046173/2578205
- Identity sample app: https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/identity

**Comment by Glavin001** [comment]
FINALLY.

I was able to follow http://stackoverflow.com/a/23877974/2578205 and ran the following commands:

``` bash
2>/dev/null openssl rsa -in extension.pem -pubout -outform DER | openssl base64 -A 
2>/dev/null openssl rsa -in extension.pem -pubout -outform DER | openssl dgst -sha256 | head -c32 | tr 0-9a-f a-p 
```

Which allowed me to add the following information to my `manifest.json` file:

``` json
  "key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsE4+Xexiri8gvx+Dly36huGmkFCegXjOnPVtm+gjbznIh6pKARNSCsr5opG6Wwah+omPq6WUnWVCKKSRXRUIRiOiONv6LerATvYKQt4QX/2xx8QSjG/IkPopcexy0voZt8U0mr31cZnMA8EXfNePAjlqcIHpI6VVgeUe0iJ0PLk1e6BUqHQdNgkL6l5+vlYHirhWmy/mGfZm8YRfQlmmWn9KkGfL/ksZKzy/LntSZf37SU6U81mreP/eXdz+neo4qpKFga2lpFEl0mfiQmANdy8FtlepsZt0x7dLbDRQ+ruOsO6xBdulLa+l6PR8WLjLS/QefQowTVCo6SGoMMKPoQIDAQAB",
  "oauth2": {
        "client_id": "gfmnnbokfmcblfmkgaldjlefgpbcjeok.apps.googleusercontent.com",
        "scopes": [
            "https://www.googleapis.com/auth/userinfo.email"
        ]
    }
```

Attached is a zip of my `extension.crx` and `extension.pem` in case I lose the `.pem` some how:
[Archive.zip](https://github.com/Glavin001/BurntChrome/files/149174/Archive.zip)

**Comment by Glavin001** [comment]
I think this was the hardest Issue. I am pushing my code now. I think we have this worked out enough.

I will need to reorganize some components for the login flow though for setup but that's tomorrow's problem.

**Comment by occamrazor1492** [comment]
https://developers.google.com/identity/sign-in/web/sign-in
I try this tutorial tonight and I think form this one we can get the users' information also they can logout, but still not figure out yet

**Comment by Glavin001** [comment]
This issue is what is causing me trouble: http://stackoverflow.com/a/27809782/2578205
Chrome is remember the profile I have logged in as. I want it to forget and logout.

**Comment by Glavin001** [comment]
Basically the logout does not work.
Once your login with a Google Account, it pairs it with Google Chrome and creates a Profile for it! Then when you logout, it doesn't. I've tried so many ways of logging out, and non of them work
So essentially someone hits the "login" button and it logs in as the admin, without prompting for password. that is the security provided.

**Comment by Glavin001** [comment]
Prototyping proved that using Google authentication will not work.
